loom {
    accessWidenerPath = file('src/main/resources/manascore_config.accesswidener')
}

dependencies {
    implementation "com.electronwill.night-config:core:3.6.6"
    implementation "com.electronwill.night-config:toml:3.6.6"
    implementation(project(path: ":network-common", configuration: 'namedElements')) { transitive false }
}