/*
 * Copyright (c) 2025. ManasMods
 * GNU General Public License 3
 */

pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://files.minecraftforge.net/maven/" }
        gradlePluginPortal()
    }
}

rootProject.name = 'manascore'

["registry", "keybinding", "network", "storage", "testing", "inventory", "skill", "config", "command"].forEach { module ->
    include ":$module-common"
    include ":$module-fabric"
    include ":$module-neoforge"
}
