/*
 * Copyright (c) 2025. ManasMods
 * GNU General Public License 3
 */

loom {
    mods {
        project(":testing-common").includedProjects.forEach {
            def moduleProject = project("$it-neoforge")
            register(moduleProject.name) {
                sourceSet("main", moduleProject)
            }
        }
    }

    runs {
        data {
            data()
            programArgs "--all", "--mod", "manascore-testing"
            programArgs "--output", project(':testing-common').file('src/generated/resources').absolutePath
            programArgs "--existing", project(':testing-common').file('src/main/resources').absolutePath
        }
    }
}

dependencies {
    project(":testing-common").includedProjects.forEach {
        common(project(path: "$it-common", configuration: 'namedElements'))
        implementation(project(path: "$it-neoforge", configuration: 'namedElements'))
    }
}
