/*
 * Copyright (c) 2025. ManasMods
 * GNU General Public License 3
 */

loom {
    accessWidenerPath = project(":skill-common").loom.accessWidenerPath
}

dependencies {
    implementation project(path: ":network-common", configuration: 'transformProductionNeoForge')
    implementation project(path: ":storage-common", configuration: 'transformProductionNeoForge')
}

remapJar {
    atAccessWideners.add("${project.mod_id}.accesswidener")
}
