/*
 * Copyright (c) 2025. ManasMods
 * GNU General Public License 3
 */

package io.github.manasmods.manascore.command;

import com.mojang.brigadier.arguments.*;
import com.mojang.brigadier.context.CommandContext;
import com.mojang.brigadier.exceptions.CommandSyntaxException;
import com.mojang.brigadier.exceptions.SimpleCommandExceptionType;
import dev.architectury.event.events.common.CommandRegistrationEvent;
import io.github.manasmods.manascore.command.api.CommandArgumentRegistrationEvent;
import io.github.manasmods.manascore.command.api.parameter.*;
import io.github.manasmods.manascore.command.api.parameter.coordinate.BlockPosArg;
import io.github.manasmods.manascore.command.api.parameter.coordinate.RotationArg;
import io.github.manasmods.manascore.command.api.parameter.coordinate.Vec3Arg;
import io.github.manasmods.manascore.command.api.parameter.primitive.*;
import io.github.manasmods.manascore.command.api.parameter.resource.*;
import io.github.manasmods.manascore.command.internal.CommandArgumentRegistry;
import net.minecraft.commands.CommandSource;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.Commands;
import net.minecraft.commands.arguments.*;
import net.minecraft.commands.arguments.blocks.BlockInput;
import net.minecraft.commands.arguments.blocks.BlockStateArgument;
import net.minecraft.commands.arguments.coordinates.BlockPosArgument;
import net.minecraft.commands.arguments.coordinates.Coordinates;
import net.minecraft.commands.arguments.coordinates.RotationArgument;
import net.minecraft.commands.arguments.coordinates.Vec3Argument;
import net.minecraft.commands.arguments.item.ItemArgument;
import net.minecraft.commands.arguments.item.ItemInput;
import net.minecraft.commands.arguments.selector.EntitySelector;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Holder;
import net.minecraft.core.particles.ParticleOptions;
import net.minecraft.core.registries.Registries;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.Tag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.phys.Vec3;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.lang.reflect.InvocationTargetException;
import java.util.UUID;

public class ManasCoreCommand {
    public static final Logger LOG = LoggerFactory.getLogger("ManasCore - Command");

    public static void init() {
        CommandArgumentRegistrationEvent.EVENT.register((registry, dispatcher, buildContext) -> {
            // Register Literal Argument
            registry.register(String.class, LiteralArg.class, (annotation, handler) -> {
                var literals = annotation.value();

                for (var literal : literals) {
                    handler.addNode(Commands.literal(literal));
                    handler.addValueExtractorToLastNode(context -> literal);
                }
            });

            // Register Sender Argument
            registry.register(CommandSourceStack.class, SenderArg.class, (annotation, handler) -> handler.addValueExtractor(CommandContext::getSource));
            registry.register(ServerPlayer.class, SenderArg.class, (annotation, handler) -> {
                handler.addValueExtractor(context -> context.getSource().getPlayerOrException());
                handler.preventConsoleUsage();
            });
            registry.register(CommandSource.class, SenderArg.class, (annotation, handler) -> handler.addValueExtractor(commandContext -> commandContext.getSource().source));

            // Register UUID Argument
            registry.register(UUID.class, UuidArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, StringArgumentType.word()));
                handler.addValueExtractorToLastNode(commandContext -> {
                    var uuidString = StringArgumentType.getString(commandContext, argumentName);
                    try {
                        return UUID.fromString(uuidString);
                    } catch (Exception e) {
                        throw new CommandSyntaxException(new SimpleCommandExceptionType(e::getMessage), e::getMessage);
                    }
                });
            });

            // Register Boolean Argument
            registry.register(Boolean.class, BooleanArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, BoolArgumentType.bool()));
                handler.addValueExtractor(commandContext -> BoolArgumentType.getBool(commandContext, argumentName));
            });
            registry.register(boolean.class, BooleanArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, BoolArgumentType.bool()));
                handler.addValueExtractor(commandContext -> BoolArgumentType.getBool(commandContext, argumentName));
            });

            // Register Text Argument
            registry.register(String.class, TextArg.class, (annotation, handler) -> {
                var argumentName = annotation.name().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.name();

                switch (annotation.value()) {
                    case WORD -> handler.addNode(
                            Commands.argument(argumentName, StringArgumentType.word())
                    );
                    case STRING -> handler.addNode(
                            Commands.argument(argumentName, StringArgumentType.string())
                    );
                    case GREEDY_STRING -> handler.addNode(
                            Commands.argument(argumentName, StringArgumentType.greedyString())
                    );
                }

                handler.addValueExtractor(commandContext -> StringArgumentType.getString(commandContext, argumentName));
            });

            // Register Double Argument
            registry.register(Double.class, DoubleArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, DoubleArgumentType.doubleArg(annotation.min(), annotation.max())));
                handler.addValueExtractor(commandContext -> DoubleArgumentType.getDouble(commandContext, argumentName));
            });
            registry.register(double.class, DoubleArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, DoubleArgumentType.doubleArg(annotation.min(), annotation.max())));
                handler.addValueExtractor(commandContext -> DoubleArgumentType.getDouble(commandContext, argumentName));
            });

            // Register Float Argument
            registry.register(Float.class, FloatArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, FloatArgumentType.floatArg(annotation.min(), annotation.max())));
                handler.addValueExtractor(commandContext -> FloatArgumentType.getFloat(commandContext, argumentName));
            });
            registry.register(float.class, FloatArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, FloatArgumentType.floatArg(annotation.min(), annotation.max())));
                handler.addValueExtractor(commandContext -> FloatArgumentType.getFloat(commandContext, argumentName));
            });

            // Register Integer Argument
            registry.register(Integer.class, IntegerArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, IntegerArgumentType.integer(annotation.min(), annotation.max())));
                handler.addValueExtractor(commandContext -> IntegerArgumentType.getInteger(commandContext, argumentName));
            });
            registry.register(int.class, IntegerArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, IntegerArgumentType.integer(annotation.min(), annotation.max())));
                handler.addValueExtractor(commandContext -> IntegerArgumentType.getInteger(commandContext, argumentName));
            });

            // Register Long Argument
            registry.register(Long.class, LongArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, LongArgumentType.longArg(annotation.min(), annotation.max())));
                handler.addValueExtractor(commandContext -> LongArgumentType.getLong(commandContext, argumentName));
            });
            registry.register(long.class, LongArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, LongArgumentType.longArg(annotation.min(), annotation.max())));
                handler.addValueExtractor(commandContext -> LongArgumentType.getLong(commandContext, argumentName));
            });

            // Register Entity Argument
            registry.register(EntitySelector.class, EntityArg.class, (annotation, handler) -> {
                var argumentName = annotation.name().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.name();
                switch (annotation.value()) {
                    case ENTITY -> handler.addNode(Commands.argument(argumentName, EntityArgument.entity()));
                    case ENTITIES -> handler.addNode(Commands.argument(argumentName, EntityArgument.entities()));
                    case PLAYER -> handler.addNode(Commands.argument(argumentName, EntityArgument.player()));
                    case PLAYERS -> handler.addNode(Commands.argument(argumentName, EntityArgument.players()));
                }
                handler.addValueExtractor(commandContext -> commandContext.getArgument(argumentName, EntitySelector.class));
            });

            // Register BlockPos Argument
            registry.register(BlockPos.class, BlockPosArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, BlockPosArgument.blockPos()));
                handler.addValueExtractor(commandContext -> BlockPosArgument.getBlockPos(commandContext, argumentName));
            });

            // Register Vec3 Argument
            registry.register(Vec3.class, Vec3Arg.class, (annotation, handler) -> {
                var argumentName = annotation.name().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.name();
                handler.addNode(Commands.argument(argumentName, Vec3Argument.vec3(annotation.value() == Vec3Arg.Type.CENTER)));
                handler.addValueExtractor(commandContext -> Vec3Argument.getVec3(commandContext, argumentName));
            });

            // Register Rotation Argument
            registry.register(Coordinates.class, RotationArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, RotationArgument.rotation()));
                handler.addValueExtractor(commandContext -> RotationArgument.getRotation(commandContext, argumentName));
            });

            // Register Dimension Argument
            registry.register(ServerLevel.class, DimensionArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, DimensionArgument.dimension()));
                handler.addValueExtractor(commandContext -> DimensionArgument.getDimension(commandContext, argumentName));
            });

            // Register Tag Argument
            registry.register(CompoundTag.class, CompoundTagArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, CompoundTagArgument.compoundTag()));
                handler.addValueExtractor(commandContext -> CompoundTagArgument.getCompoundTag(commandContext, argumentName));
            });
            registry.register(Tag.class, NbtTagArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, NbtTagArgument.nbtTag()));
                handler.addValueExtractor(commandContext -> NbtTagArgument.getNbtTag(commandContext, argumentName));
            });

            // Register ResourceLocation Argument
            registry.register(ResourceLocation.class, ResourceLocationArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, ResourceLocationArgument.id()));
                handler.addValueExtractor(commandContext -> ResourceLocationArgument.getId(commandContext, argumentName));
            });

            // Register Holder.Reference Argument
            registry.register(Holder.Reference.class, AttributeArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, ResourceArgument.resource(buildContext, Registries.ATTRIBUTE)));
                handler.addValueExtractor(commandContext -> ResourceArgument.getAttribute(commandContext, argumentName));
            });
            registry.register(Holder.Reference.class, DamageArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, ResourceArgument.resource(buildContext, Registries.DAMAGE_TYPE)));
                handler.addValueExtractor(commandContext -> ResourceArgument.getResource(commandContext, argumentName, Registries.DAMAGE_TYPE));
            });
            registry.register(Holder.Reference.class, EnchantmentArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, ResourceArgument.resource(buildContext, Registries.ENCHANTMENT)));
                handler.addValueExtractor(commandContext -> ResourceArgument.getEnchantment(commandContext, argumentName));
            });
            registry.register(Holder.Reference.class, MobEffectArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, ResourceArgument.resource(buildContext, Registries.MOB_EFFECT)));
                handler.addValueExtractor(commandContext -> ResourceArgument.getMobEffect(commandContext, argumentName));
            });
            registry.register(Holder.Reference.class, StructureArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, ResourceArgument.resource(buildContext, Registries.STRUCTURE)));
                handler.addValueExtractor(commandContext -> ResourceArgument.getStructure(commandContext, argumentName));
            });
            registry.register(Holder.Reference.class, FeatureArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, ResourceArgument.resource(buildContext, Registries.CONFIGURED_FEATURE)));
                handler.addValueExtractor(commandContext -> ResourceArgument.getConfiguredFeature(commandContext, argumentName));
            });

            // Register Item Argument
            registry.register(ItemInput.class, ItemArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, ItemArgument.item(buildContext)));
                handler.addValueExtractor(commandContext -> ItemArgument.getItem(commandContext, argumentName));
            });

            // Register Block Argument
            registry.register(BlockInput.class, BlockArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, BlockStateArgument.block(buildContext)));
                handler.addValueExtractor(commandContext -> BlockStateArgument.getBlock(commandContext, argumentName));
            });

            // Register Particle Argument
            registry.register(ParticleOptions.class, ParticleArg.class, (annotation, handler) -> {
                var argumentName = annotation.value().isBlank() ? handler.getAutoGeneratedArgumentName() : annotation.value();
                handler.addNode(Commands.argument(argumentName, ParticleArgument.particle(buildContext)));
                handler.addValueExtractor(commandContext -> ParticleArgument.getParticle(commandContext, argumentName));
            });
        });

        CommandRegistrationEvent.EVENT.register((dispatcher, buildContext, commandSelection) -> {
            var registry = new CommandArgumentRegistry();
            // Register Argument Annotations
            CommandArgumentRegistrationEvent.EVENT.invoker().register(registry, dispatcher, buildContext);
            // Register Commands
            CommandAnnotationHandler.COMMANDS.forEach(commandNode -> {
                try {
                    var command = commandNode.build(registry);
                    command.forEach(dispatcher::register);

                    // Register Permissions
                    commandNode.getPermissions().forEach(PlatformCommandUtils::registerPermission);
                } catch (NoSuchMethodException | InvocationTargetException | InstantiationException |
                         IllegalAccessException e) {
                    throw new RuntimeException(e);
                }
            });
        });
    }
}
