modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "manascore"
version = "${version}"
displayName = "ManasCore"
authors = "ManasMods"
description = '''
Utility and Core Library for Manas Mods
'''
logoFile = "icon.png"

[[dependencies.manascore]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.manascore]]
    modId = "minecraft"
    type = "required"
    versionRange = "[${minecraft_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.manascore]]
    modId = "architectury"
    type = "required"
    versionRange = "[${architectury_version},)"
    ordering = "AFTER"
    side = "BOTH"
