/*
 * Copyright (c) 2025. ManasMods
 * GNU General Public License 3
 */

ext {
    includedProjects = [
            ":attribute",
            ":command",
            ":config",
            ":inventory",
            ":keybind",
            ":network",
            ":storage",
            ":skill"
    ]
}

loom {
    mods {
        includedProjects.forEach {
            def moduleProject = project("$it-common")
            register(moduleProject.name) {
                sourceSet("main", moduleProject)
            }
        }
    }
}

dependencies {
    includedProjects.forEach {
        implementation(project(path: "$it-common", configuration: 'namedElements')) { transitive false }
    }
}
